Repository LofftApp/lofft-mobile-app, pull requests merged in 2022-03, with the labels that each got.

#40 re-migration done ✅
  App.js
  assets/appImages/apple_pay_logo.png
  assets/appImages/google_pay_logo.png
  assets/appImages/paypal_logo.png
  assets/appImages/sepa_logo.png
  assets/appImages/visa_logo.png
  babel.config.js
  index.js
  ios/LofftApp.xcodeproj/project.pbxproj
  ios/LofftApp/Info.plist
  package.json
  src/components/ActiveCard.tsx
  src/components/CardType.tsx
  src/components/MyCarousel.tsx
  src/components/PaymentOption.tsx
  src/components/SingleCardType.tsx
  src/components/cards/PaymentCard.tsx
  src/screens/userScreens/DashboardScreen.tsx
  src/screens/userScreens/MakePaymentScreen.tsx
  src/screens/userScreens/PaymentSelectScreen.tsx
  yarn.lock
Labels: enhancement

#55 fixed small merge issue with button location
  ios/LofftApp.xcodeproj/project.pbxproj
  src/screens/userScreens/PaymentSelectScreen.tsx
Labels: bug

#57 New user profile page
  src/StyleSheets/CoreDesignStyleSheet.js
  src/components/buttons/CustomBackButton.tsx
  src/components/containers/ScreenContainer.tsx
  src/components/iconsAndContainers/TagIcon.tsx
  src/screens/userScreens/ProfileScreen.tsx
  testData/auth_export/accounts.json
  testData/firebase-export-metadata.json
  testData/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  testData/firestore_export/all_namespaces/all_kinds/output-0
  testData/firestore_export/firestore_export.overall_export_metadata
Labels: enhancement

#58 Managementscreen
  App.js
  package.json
  src/components/UserComponents.tsx
  src/components/bannersAndBars/ToggleBar.tsx
  src/components/calendar/CalendarManagement.tsx
  src/components/cards/PollCard.tsx
  src/components/iconsAndContainers/NewPollContainer.tsx
  src/screens/userScreens/DashboardScreen.tsx
  src/screens/userScreens/MakeNewEventScreen.tsx
  src/screens/userScreens/MakeNewPollScreen.tsx
  src/screens/userScreens/ManagementScreen.tsx
  yarn.lock
Labels: enhancement

#59 Copied in the design from the user profile
  package.json
  src/screens/apartmentScreens/ViewApartmentScreen.tsx
  testData/auth_export/accounts.json
  testData/firebase-export-metadata.json
  testData/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  testData/firestore_export/all_namespaces/all_kinds/output-0
  testData/firestore_export/firestore_export.overall_export_metadata
  yarn.lock
Labels: enhancement

#56 Commented out areas that caused errors to bug fix
  App.js
  src/api/firebase/firebaseApi.ts
  src/components/UserComponents.tsx
  src/screens/financeScreens/BillOverviewsScreen.tsx
  src/screens/financeScreens/FinanceScreen.tsx
  src/screens/financeScreens/MakePaymentScreen.tsx
  src/screens/financeScreens/PaidConfirmationScreen.tsx
  src/screens/financeScreens/PaymentSelectScreen.tsx
  src/screens/financeScreens/PendingPaymentsScreen.tsx
Labels: bug

#60 Creatingpollscreen
  App.js
  ios/LofftApp.xcodeproj/project.pbxproj
  src/components/buttons/AddButtonPoll.tsx
  src/components/calendar/CalendarManagement.tsx
  src/screens/userScreens/DeadlineScreen.tsx
  src/screens/userScreens/MakeNewPollScreen.tsx
  src/screens/userScreens/ManagementScreen.tsx
Labels: enhancement

#64 Issue add new lofft
  src/api/firebase/fireStoreActions.ts
  src/screens/apartmentScreens/ViewApartmentScreen.tsx
  testData2/auth_export/accounts.json
  testData2/auth_export/config.json
  testData2/firebase-export-metadata.json
  testData2/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  testData2/firestore_export/all_namespaces/all_kinds/output-0
  testData2/firestore_export/firestore_export.overall_export_metadata
  testData2/storage_export/blobs/lofft-26eb1.appspot.com/hSQ716GThjzuetmtfUpQDt14Ku6r/userImage/profile.jpg
  testData2/storage_export/blobs/lofft-26eb1.appspot.com/rqE3CdwzKU6TyUupnWa2Sq185bQQ/userImage/profile.jpg
  testData2/storage_export/buckets.json
Labels: bug, enhancement

#65 Changed how the user admin status is added to db
  src/api/firebase/fireStoreActions.ts
  src/screens/apartmentScreens/ViewApartmentScreen.tsx
Labels: enhancement

#67 Management screen ii
  App.js
  assets/sampleFaces/adam.jpg
  assets/sampleFaces/freddie.jpg
  assets/sampleFaces/james.jpg
  assets/sampleFaces/may.jpg
  src/components/buttons/CoreButton.tsx
  src/components/calendar/CalendarManagement.tsx
  src/components/cards/ImageFriendContainer.tsx
  src/screens/managementScreens/AddFriendsScreen.tsx
  src/screens/managementScreens/DeadlineScreen.tsx
  src/screens/managementScreens/EventConfirmationScreen.tsx
  src/screens/managementScreens/MakeNewEventScreen.tsx
  src/screens/managementScreens/MakeNewPollScreen.tsx
  src/screens/managementScreens/PollConfirmationScreen.tsx
  src/screens/userScreens/MakeNewEventScreen.tsx
  src/screens/userScreens/ManagementScreen.tsx
Labels: enhancement

#66 Lofft primary user config page
  src/api/firebase/fireStoreActions.ts
  src/assets/defaultColorPallet.json
  src/components/HobbiesAndValues.tsx
  src/data/hobbiesAndValues.json
  src/screens/apartmentScreens/AddApartmentScreen.tsx
  src/screens/apartmentScreens/ViewApartmentScreen.tsx
  testData2/auth_export/accounts.json
  testData2/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  testData2/firestore_export/all_namespaces/all_kinds/output-0
  testData2/firestore_export/firestore_export.overall_export_metadata
Labels: enhancement

#68 Create page edit component
  src/components/buttons/EditPageButton.tsx
  src/screens/apartmentScreens/ViewApartmentScreen.tsx
  src/screens/userScreens/ProfileScreen.tsx
Labels: enhancement
